### ISSUE TITLE
[Navbar unusually tall]

### ISSUE THREAD

**Issue by rvvergara** [azdrenymeri/social-network#10]
![image](https://user-images.githubusercontent.com/6015315/59571576-d9a02e80-90d8-11e9-8aab-a9effa245dd2.png)

Rightmost selections are stacked on top of each other when there's a huge amount of space further to the right of the navbar. The effect is that the navbar itself has become very tall

**Comment by azdrenymeri** [comment]
Can you tell me how you produced this error 
Below I stretched my side across my two screens 
![csrsh](https://i.ibb.co/ydm7Xx5/Screenshot-from-2019-06-17-11-13-43.png)
