### ISSUE TITLE
[Error when accepting a friend request]

### ISSUE THREAD

**Issue by rvvergara** [azdrenymeri/social-network#12]
This is what happens the moment I click the "Accept" button on a friend request

![image](https://user-images.githubusercontent.com/6015315/59730323-8531b600-9274-11e9-94a0-7bf227b27ebf.png)

The reason for this is we changed the `change_status` into an instance method but we're still calling it as a `class` method in the view

**Comment by azdrenymeri** [comment]
Fixed
