### ISSUE TITLE
[Error when accepting a friend request - It happened again]

### ISSUE THREAD

**Issue by rvvergara** [azdrenymeri/social-network#14]
Hi @azdrenymeri and @milosvukadinovic,

I highly recommend not closing an issue right away until I confirm that indeed all errors are gone. It's hard to keep up with issues if we close it without confirming from both your side and my side that all is well. 

Anyhow, here's what I get now when I click the Accept button

![image](https://user-images.githubusercontent.com/6015315/59984273-da960a80-965a-11e9-84bb-c2f8c279d133.png)

This error is related to my previous review about your `friendships_controller.rb` `index` action (`@friendship` variable). I don't think you guys have fixed that one.

**Comment by azdrenymeri** [comment]
Fixed

**Comment by rvvergara** [comment]
I confirm that it is indeed fixed.. Great job guys!
