### ISSUE TITLE
[I am redirected to an exception page when sending a request to someone i've requested already]

### ISSUE THREAD

**Issue by rvvergara** [azdrenymeri/social-network#7]
Related to #6, when I click that `Send Request` button again I am led to this page:

![image](https://user-images.githubusercontent.com/6015315/58771097-04708a00-85e5-11e9-94ca-e4e3ed1dfe37.png)

We want to show a flash message instead and we should be redirected to a valid app page and not a rails exception page as above.

**Comment by azdrenymeri** [comment]
Fixed
